### ISSUE TITLE
Reavim referencing missing reaper-keys files

### ISSUE THREAD

**Issue by 0atman** [AntoineBalaine/perken-reaper-scripts#13]
Hi @AntoineBalaine - I've rediscovered your fork after a year or two - thanks for making it a reapack!

However, after a seamless install, some things don't work, seemingly referencing old `reaper-keys` files?

Like here, with `SPC dD`, for dynamic split:

![Screenshot from 2024-04-18 18-44-12](https://github.com/AntoineBalaine/perken-reaper-scripts/assets/114097/3cff0bbd-202c-4b2a-ad12-17bf214b0c37)

I'm hoping this could be a simple fix as Reavim otherwise works great, the which-key UI, track navigation and `M-x` etc.

Thank you!

## My Environment

- Reaper:  v7.11 - February 10 2024 (latest as of today)
- O/S: Linux (nixos)
- Reapack: 1.2.4.5 (latest)
- Reavim: 0.0.2 (latest)

**Comment by 0atman** [comment]
oh! I notice the little _which-key_ window is called "reaper keys" too!

**Comment by AntoineBalaine** [comment]
Hello @0atman, 
Yes, I didn't update much of the naming after I did the reapack setup. Were you able to get it running though?

If you still have the old reaper-keys version in your actions list, I'd recommend removing it, and then pulling the updated version from my fork. 

Also, on macos, the keymap has some issues with mapping shift keys (e.g. `S-[a-z]`). I remember making an update to the keymap file to sort it out. On linux, it should be okay - I've been using it on my system and everything seems to be working good.

If the issue persists though, please let me know. We can get in touch via the reascript discord if that's easier.

**Comment by 0atman** [comment]
Fresh install: It does install and basic functionality works (navigating with `w` and `b`, deleting with `d` etc, but some actions (like dynamic split here) seem to still be mapped to the old `reaper-keys` folder structure?

I'm going to do some editing today, and I'll try to use reavim exclusively to see what works and what doesn't.

**Comment by AntoineBalaine** [comment]
Oh, I see the problem. I pushed a fix on my reapack, let me know if that sorts it out.

**Comment by 0atman** [comment]
@AntoineBalaine no change, but maybe that's my fault? Here's what I did:

## 1. Syncronised my repacks, which updated reavim

![image](https://github.com/AntoineBalaine/perken-reaper-scripts/assets/114097/f4e79b29-ca7d-4268-b396-f14e67b11ff3)

## 2. Cleared my keymap and re-imported keymap from `~/.config/REAPER/scripts/perken/reavim/reavim-unix.ReaperKeyMap`

![image](https://github.com/AntoineBalaine/perken-reaper-scripts/assets/114097/a6941dca-0a66-467d-bcea-3f71915f2235)

## 3. Tested `spc d D` again, same error

![Screenshot from 2024-04-22 15-07-31](https://github.com/AntoineBalaine/perken-reaper-scripts/assets/114097/85dbf479-13f1-40eb-90c7-50e88e8c30ba)

**Comment by AnthonyBalaine** [comment]
Can you try to pull the branch directly, instead of going through reapack? It might be that I messed up the version.

**Comment by AntoineBalaine** [comment]
Can you try to pull the branch directly, instead of going through reapack? It might be that I messed up the version.

**Comment by 0atman** [comment]
can do, trying that out now ...

**Comment by AntoineBalaine** [comment]
If this still doesn’t get you unblocked, you’re welcome to find me on the reascript discord - I’ll be happy to help you over a screen-share session.

**Comment by 0atman** [comment]
Thank you so much for the offer, I'll ping you if I can't get to the bottom of it myself.
Here's all the `reaper-keys` strings,  I can't see anything suspicious. Both keymap files (omitted for space) reference the correct path, for example?:

```csv
2111:SCR   4                0                 "_reaper_keys_main_<S-X>"          "[reaper-keys]  [key_press]  [X]"                ./perken/reavim/key_scripts/main_(S-x).lua
```

```sh
 ❯ rg reaper-keys
reavim.lua
13:    Since this project is a fork of https://github.com/gwatcha/reaper-keys, please refer to the original documentation for installation and usage.
16:    Gwatcha's original reaper-keys repo https://github.com/gwatcha/reaper-keys
18:    0.0.3 Keymap: fix paths that were still referring to reaper-keys' path

Rakefile
10:@keymap_path = 'reaper-keys.ReaperKeyMap'
24:  `zip -r dist/reaper-keys.zip * -x dist img/* img`

definitions/bindings.lua
3:-- if you need help, check out the documentation https://gwatcha.github.io/reaper-keys/configuration/bindings.html

scripts/generator.rb
78:    desc = "[reaper-keys] [key_press] [#{key}]"
99:local doInput = require('internal.reaper-keys')

README.md
4:  <img src="img/reaper-keys.png">
38:With reaper-keys, you may bind key sequences to actions, rather then singular
88:- Clone this repository or download it via the 'releases' tab (download the file 'reaper-keys.zip').
90:- Back up your key map by exporting it, then import the provided keymap `reaper-keys.ReaperKeyMap` via the `import` button at the bottom of the action list window in Reaper. (This will overwrite your current key bindings!)
93:When you restore your old keymap, you may want to empty the `reaper-kb.ini` in your `REAPER` root directory and restart REAPER. Otherwise, there will likely be remnants from reaper-keys.
109:Check out the [documentation](https://gwatcha.github.io/reaper-keys) to learn more.

definitions/config.lua
3:-- https://gwatcha.github.io/reaper-keys/configuration/behaviour.html

definitions/actions.lua
3:-- if you need help check out the documentation https://gwatcha.github.io/reaper-keys/configuration/actions.html

docs/README.md
1:Welcome to the documentation for reaper-keys, a plugin for Reaper that improves the key binding system.

docs/configuration/behaviour.md
18:The `config` file has a table of options that tweaks reaper-keys behaviour.

internal/gui/feedback/controller.lua
71:      reaper.ShowMessageBox("Hello from inside Reaper Keys! I see the feedback window just opened... Here are some things I have been told to tell you:\n  -If the feedback window is focused, I can't hear the keys being pressed, so be sure to unfocus it.\n  -If that pesky 'this script is running in the background hur dur' message comes up just check 'new instance' and 'remember' and it will go away\n  -Press <M-x> (Alt+x) to open up a keybinding menu.\n  -Everything you need to configure reaper-keys is in the REAPER/Scripts/reaper-keys/definitions/ directory.\n  -If you would like this message to not appear anymore, set the option in definitions/config.lua.\n  -If you set that option there will be no one to protect you from the focus stealing of the feedback window.\n  -reaper-keys uses a reduced keymap by default, if you want more keybindings, set the option in definitions/config.lua to use the extended defaults.\n  -Your mother loves you", "Reaper Keys Open Message", 1)

internal/command/handler.lua
52:	reaper.Undo_EndBlock("reaper-keys: " .. format.commandDescription(command), 1)

docs/action_composition.md
8:The main feature reaper-keys provides is the ability to compose actions of different types to create new commands.
10:How one can compose action types (i.e. the available _action sequences_) and their behaviour when joined is dependant on the [mode](modes) of reaper-keys.
16:There are various action types in reaper-keys.

docs/configuration.md
18:These files contain lua tables that may be altered to change or add key bindings, actions, or tweak reaper-keys behaviour.
20:Read on to learn how to configure a particular aspect of reaper-keys.
```

**Comment by AntoineBalaine** [comment]
Yes, the keymap file’s example here points to the correct path.
I don’t see anything suspicious either - I tried a fresh reapack install on a MacOS machine, and everything’s working fine. 

When you imported the updated keymap, did you remember to remove all previous `reaper-keys` actions from your actions’ list?

**Comment by 0atman** [comment]
I believe I did, I selected "Reset all shortcuts in all sections to defaults", maybe I'll try an alternative way.

![image](https://github.com/AntoineBalaine/perken-reaper-scripts/assets/114097/00d6fff7-b0c8-4098-96e8-c67afdc3dba6)

**Comment by AntoineBalaine** [comment]
That’s not quite what I mean - try to search for `reaper-keys` in the actions list, select all the actions, hit the `delete` button and then import the updated keymap for all sections.

**Comment by 0atman** [comment]
You've got it! I'm so sorry, I see that reseting all to defaults doesn't do it - because reaper-keys isn't default!

Thank you so much for your help it works!!!

![image](https://github.com/AntoineBalaine/perken-reaper-scripts/assets/114097/e71b09cc-1a6a-4143-8310-49679fcffe07)

**Comment by AntoineBalaine** [comment]
That’s wonderful. I’d be curious to hear your feedback after you take the project for a spin. 
Have fun ;-)

**Comment by 0atman** [comment]
I'll certainly give you feedback if I find anything!
I've just been hit with some bad RSI due to editing, so I'm going to use reavim in ernest!
